#!/bin/bash

# Add to the .git/hooks directory and ensure executable script

protected_branch='master'
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ $protected_branch = $current_branch ]
then
    echo "You cannot push directly to the master branch. Open a pull request."
    exit 1
else
    exit 0 # push will execute
fi
